org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.1
minecraft_version_range=[26.1.1]
neo_version=26.1.1.10-beta

mod_id=squakeported
mod_name=Squake Ported
mod_license=All Rights Reserved
mod_version=1-26.1.1-neoforge
mod_group_id=mett.palemannie.squakeported
